export const allProducts = {
  sanitary: [
    {
      id: 1,
      name: "SP-NC95",
      brand: "MedicalPro",
      thickness: "5mm",
      finish: "Clear",
      price: 189.99,
      originalPrice: 229.99,
      discount: 17,
      image: "/prod1.png",
      inStock: true,
      stockCount: 24,
      badges: ["Medical Grade", "FDA Approved"],
      delivery: "Express Delivery",
      description:
        "Premium medical-grade acrylic designed for healthcare environments with superior hygiene properties.",
      specifications: {
        "Light Transmission": "92%",
        "Impact Strength": "High",
        "Chemical Resistance": "Excellent",
        "UV Resistance": "Yes",
      },
      sizes: [
        {
          name: "2' × 4'",
          price: 89.99,
          inStock: true,
          stockCount: 15,
          dimensions: '24" × 48"',
        },
        {
          name: "4' × 8'",
          price: 189.99,
          inStock: true,
          stockCount: 24,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 299.99,
          inStock: true,
          stockCount: 8,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 449.99,
          inStock: false,
          stockCount: 0,
          dimensions: '72" × 144"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
    {
      id: 2,
      name: "SP-NB30",
      brand: "HygieneShield",
      category: "Antibacterial",
      thickness: "3mm",
      finish: "Frosted",
      size: "4' × 8'",
      price: 159.99,
      originalPrice: 189.99,
      discount: 16,
      image: "/prod2.png",
      rating: 4.7,
      reviews: 89,
      inStock: true,
      stockCount: 18,
      features: [
        "Antimicrobial",
        "Privacy Protection",
        "Easy Maintenance",
        "Scratch Resistant",
      ],
      badges: ["Antibacterial", "New"],
      delivery: "2-Day Delivery",
      description:
        "Advanced antibacterial frosted acrylic perfect for privacy screens and hygienic applications.",
      specifications: {
        "Light Transmission": "65%",
        "Antibacterial Efficacy": "99.9%",
        "Surface Hardness": "High",
        Maintenance: "Low",
      },
      sizes: [
        {
          name: "2' × 4'",
          price: 79.99,
          inStock: true,
          stockCount: 12,
          dimensions: '24" × 48"',
        },
        {
          name: "4' × 8'",
          price: 159.99,
          inStock: true,
          stockCount: 18,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 249.99,
          inStock: true,
          stockCount: 6,
          dimensions: '60" × 120"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
    {
      id: 3,
      name: "SP-B857",
      brand: "ClinicalClear",
      category: "Hospital Grade",
      thickness: "8mm",
      finish: "White",
      size: "5' × 10'",
      price: 299.99,
      originalPrice: 359.99,
      discount: 17,
      image: "/prod3.png",
      rating: 4.8,
      reviews: 203,
      inStock: true,
      stockCount: 12,
      features: [
        "Hospital Approved",
        "Fire Retardant",
        "Non-Porous",
        "Sterilizable",
      ],
      badges: ["Hospital Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Premium hospital-grade white acrylic meeting the highest medical facility standards.",
      specifications: {
        "Fire Rating": "Class A",
        Sterilization: "Compatible",
        Porosity: "Non-Porous",
        Durability: "Excellent",
      },
      sizes: [
        {
          name: "3' × 6'",
          price: 149.99,
          inStock: true,
          stockCount: 20,
          dimensions: '36" × 72"',
        },
        {
          name: "4' × 8'",
          price: 229.99,
          inStock: true,
          stockCount: 15,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 299.99,
          inStock: true,
          stockCount: 12,
          dimensions: '60" × 120"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
    {
      id: 4,
      name: "SP-NB00",
      brand: "BioProtect",
      category: "Antimicrobial",
      thickness: "6mm",
      finish: "Clear",
      size: "4' × 8'",
      price: 219.99,
      originalPrice: 269.99,
      discount: 19,
      image: "/prod4.png",
      rating: 4.6,
      reviews: 127,
      inStock: true,
      stockCount: 31,
      features: [
        "99.9% Germ Protection",
        "Self-Cleaning",
        "Transparent",
        "Long-lasting",
      ],
      badges: ["Antimicrobial", "Best Seller"],
      delivery: "Same Day",
      description:
        "Revolutionary antimicrobial clear acrylic with self-cleaning properties for maximum protection.",
      specifications: {
        "Germ Protection": "99.9%",
        "Self-Cleaning": "Yes",
        Transparency: "Crystal Clear",
        Lifespan: "10+ Years",
      },
      sizes: [
        {
          name: "2' × 4'",
          price: 109.99,
          inStock: true,
          stockCount: 25,
          dimensions: '24" × 48"',
        },
        {
          name: "4' × 8'",
          price: 219.99,
          inStock: true,
          stockCount: 31,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 349.99,
          inStock: true,
          stockCount: 18,
          dimensions: '60" × 120"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],
  interior: [
    {
      id: 7,
      name: "L-001",
      brand: "ClearVision",
      category: "Interior Design",
      thickness: "6mm",
      finish: "Clear",
      size: "4' × 8'",
      price: 249.99,
      originalPrice: 299.99,
      discount: 17,
      image:
        "/placeholder.svg?height=600&width=600&text=Crystal+Clear+Interior",
      rating: 4.8,
      reviews: 142,
      inStock: true,
      stockCount: 28,
      features: [
        "99.9% Clarity",
        "UV Resistant",
        "Scratch Resistant",
        "Easy Installation",
      ],
      badges: ["Premium", "Crystal Clear"],
      delivery: "Express Delivery",
      description:
        "Premium crystal-clear acrylic perfect for modern interior design applications.",
      specifications: {
        "Light Transmission": "99.9%",
        "UV Protection": "Yes",
        "Scratch Resistance": "High",
        Installation: "Easy",
      },
      sizes: [
        {
          name: "2' × 4'",
          price: 119.99,
          inStock: true,
          stockCount: 35,
          dimensions: '24" × 48"',
        },
        {
          name: "4' × 8'",
          price: 249.99,
          inStock: true,
          stockCount: 28,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 389.99,
          inStock: true,
          stockCount: 15,
          dimensions: '60" × 120"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
    {
      id: 8,
      name: "Frosted Privacy Screen",
      brand: "PrivacyPro",
      category: "Privacy Solutions",
      thickness: "5mm",
      finish: "Frosted",
      size: "4' × 8'",
      price: 199.99,
      originalPrice: 239.99,
      discount: 17,
      image: "/placeholder.svg?height=600&width=600&text=Frosted+Privacy",
      rating: 4.6,
      reviews: 98,
      inStock: true,
      stockCount: 35,
      features: [
        "Privacy Protection",
        "Light Diffusion",
        "Modern Design",
        "Custom Sizes",
      ],
      badges: ["Privacy", "Modern"],
      delivery: "2-Day Delivery",
      description:
        "Elegant frosted acrylic for privacy screens and modern interior partitions.",
      specifications: {
        "Light Transmission": "70%",
        "Privacy Level": "High",
        Design: "Modern",
        Customization: "Available",
      },
      sizes: [
        {
          name: "2' × 4'",
          price: 99.99,
          inStock: true,
          stockCount: 42,
          dimensions: '24" × 48"',
        },
        {
          name: "4' × 8'",
          price: 199.99,
          inStock: true,
          stockCount: 35,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 319.99,
          inStock: true,
          stockCount: 18,
          dimensions: '60" × 120"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],
  advertising: [
    {
      id: 9,
      name: "LED Compatible Display Panel",
      brand: "SignPro",
      category: "LED Displays",
      thickness: "8mm",
      finish: "Clear",
      size: "5' × 10'",
      price: 399.99,
      originalPrice: 479.99,
      discount: 17,
      image: "/placeholder.svg?height=600&width=600&text=LED+Display+Panel",
      rating: 4.9,
      reviews: 203,
      inStock: true,
      stockCount: 15,
      features: [
        "LED Compatible",
        "Weather Resistant",
        "High Impact",
        "UV Stable",
      ],
      badges: ["LED Ready", "Weather Proof"],
      delivery: "Express Delivery",
      description:
        "Professional-grade acrylic designed for LED-backlit advertising displays.",
      specifications: {
        "LED Compatibility": "Yes",
        "Weather Rating": "IP65",
        "Impact Strength": "High",
        "UV Stability": "Excellent",
      },
      sizes: [
        {
          name: "3' × 6'",
          price: 199.99,
          inStock: true,
          stockCount: 25,
          dimensions: '36" × 72"',
        },
        {
          name: "4' × 8'",
          price: 299.99,
          inStock: true,
          stockCount: 20,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 399.99,
          inStock: true,
          stockCount: 15,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],
  heatcut: [
    {
      id: 10,
      name: "Classic Brown 570 ",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/570.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 11,
      name: "Royal Blue B703",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/b703.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],
    nature: [
    {
      id: 12,
      name: "Classic Brown 570 ",
      brand: "Nature Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/nt002.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 13,
      name: "Royal Blue B703",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/nt001.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],

      superior: [
    {
      id: 14,
      name: "Light Brown SP-NC95",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior1.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 15,
      name: "Foggy Brown SP-NB30",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior02.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
           {
      id: 15,
      name: "Marine Blue SP-B857",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior03.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
  ],
};

export const productList = [
  {
    id: 1,
    name: "SP-NC95",
    brand: "Buidling Material",
    thickness: "5mm",
    finish: "Clear",
    price: 189.99,
    originalPrice: 229.99,
    discount: 17,
    image: "/prod1.png",
    inStock: true,
    stockCount: 24,
    badges: ["Medical Grade", "FDA Approved"],
    delivery: "Express Delivery",
    description:
      "Premium medical-grade acrylic designed for healthcare environments with superior hygiene properties.",
    specifications: {
      "Light Transmission": "92%",
      "Impact Strength": "High",
      "Chemical Resistance": "Excellent",
      "UV Resistance": "Yes",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 89.99,
        inStock: true,
        stockCount: 15,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 189.99,
        inStock: true,
        stockCount: 24,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 299.99,
        inStock: true,
        stockCount: 8,
        dimensions: '60" × 120"',
      },
      {
        name: "6' × 12'",
        price: 449.99,
        inStock: false,
        stockCount: 0,
        dimensions: '72" × 144"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 2,
    name: "SP-NB30",
    brand: "Buidling Material",
    category: "Antibacterial",
    thickness: "3mm",
    finish: "Frosted",
    size: "4' × 8'",
    price: 159.99,
    originalPrice: 189.99,
    discount: 16,
    image: "/prod2.png",
    rating: 4.7,
    reviews: 89,
    inStock: true,
    stockCount: 18,
    features: [
      "Antimicrobial",
      "Privacy Protection",
      "Easy Maintenance",
      "Scratch Resistant",
    ],
    badges: ["Antibacterial", "New"],
    delivery: "2-Day Delivery",
    description:
      "Advanced antibacterial frosted acrylic perfect for privacy screens and hygienic applications.",
    specifications: {
      "Light Transmission": "65%",
      "Antibacterial Efficacy": "99.9%",
      "Surface Hardness": "High",
      Maintenance: "Low",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 79.99,
        inStock: true,
        stockCount: 12,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 159.99,
        inStock: true,
        stockCount: 18,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 249.99,
        inStock: true,
        stockCount: 6,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 3,
    name: "SP-B857",
    brand: "Buidling Material",
    category: "Hospital Grade",
    thickness: "8mm",
    finish: "White",
    size: "5' × 10'",
    price: 299.99,
    originalPrice: 359.99,
    discount: 17,
    image: "/prod3.png",
    rating: 4.8,
    reviews: 203,
    inStock: true,
    stockCount: 12,
    features: [
      "Hospital Approved",
      "Fire Retardant",
      "Non-Porous",
      "Sterilizable",
    ],
    badges: ["Hospital Grade", "Fire Safe"],
    delivery: "Express Delivery",
    description:
      "Premium hospital-grade white acrylic meeting the highest medical facility standards.",
    specifications: {
      "Fire Rating": "Class A",
      Sterilization: "Compatible",
      Porosity: "Non-Porous",
      Durability: "Excellent",
    },
    sizes: [
      {
        name: "3' × 6'",
        price: 149.99,
        inStock: true,
        stockCount: 20,
        dimensions: '36" × 72"',
      },
      {
        name: "4' × 8'",
        price: 229.99,
        inStock: true,
        stockCount: 15,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 299.99,
        inStock: true,
        stockCount: 12,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 4,
    name: "SP-NB00",
    brand: "Buidling Material",
    category: "Antimicrobial",
    thickness: "6mm",
    finish: "Clear",
    size: "4' × 8'",
    price: 219.99,
    originalPrice: 269.99,
    discount: 19,
    image: "/prod4.png",
    rating: 4.6,
    reviews: 127,
    inStock: true,
    stockCount: 31,
    features: [
      "99.9% Germ Protection",
      "Self-Cleaning",
      "Transparent",
      "Long-lasting",
    ],
    badges: ["Antimicrobial", "Best Seller"],
    delivery: "Same Day",
    description:
      "Revolutionary antimicrobial clear acrylic with self-cleaning properties for maximum protection.",
    specifications: {
      "Germ Protection": "99.9%",
      "Self-Cleaning": "Yes",
      Transparency: "Crystal Clear",
      Lifespan: "10+ Years",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 109.99,
        inStock: true,
        stockCount: 25,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 219.99,
        inStock: true,
        stockCount: 31,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 349.99,
        inStock: true,
        stockCount: 18,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 7,
    name: "L-001",
    brand: "Interior",
    category: "Interior Design",
    thickness: "6mm",
    finish: "Clear",
    size: "4' × 8'",
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    image: "/g409.png",
    rating: 4.8,
    reviews: 142,
    inStock: true,
    stockCount: 28,
    features: [
      "99.9% Clarity",
      "UV Resistant",
      "Scratch Resistant",
      "Easy Installation",
    ],
    badges: ["Premium", "Crystal Clear"],
    delivery: "Express Delivery",
    description:
      "Premium crystal-clear acrylic perfect for modern interior design applications.",
    specifications: {
      "Light Transmission": "99.9%",
      "UV Protection": "Yes",
      "Scratch Resistance": "High",
      Installation: "Easy",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 119.99,
        inStock: true,
        stockCount: 35,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 249.99,
        inStock: true,
        stockCount: 28,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 389.99,
        inStock: true,
        stockCount: 15,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 8,
    name: "ND 31",
    brand: "Sanitary",
    category: "Privacy Solutions",
    thickness: "5mm",
    finish: "Frosted",
    size: "4' × 8'",
    price: 199.99,
    originalPrice: 239.99,
    discount: 17,
    image: "/347.png",
    rating: 4.6,
    reviews: 98,
    inStock: true,
    stockCount: 35,
    features: [
      "Privacy Protection",
      "Light Diffusion",
      "Modern Design",
      "Custom Sizes",
    ],
    badges: ["Privacy", "Modern"],
    delivery: "2-Day Delivery",
    description:
      "Elegant frosted acrylic for privacy screens and modern interior partitions.",
    specifications: {
      "Light Transmission": "70%",
      "Privacy Level": "High",
      Design: "Modern",
      Customization: "Available",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 99.99,
        inStock: true,
        stockCount: 42,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 199.99,
        inStock: true,
        stockCount: 35,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 319.99,
        inStock: true,
        stockCount: 18,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
  {
    id: 9,
    name: "ND 33",
    brand: "Sanitary",
    category: "LED Displays",
    thickness: "8mm",
    finish: "Clear",
    size: "5' × 10'",
    price: 399.99,
    originalPrice: 479.99,
    discount: 17,
    image: "/208.png",
    rating: 4.9,
    reviews: 203,
    inStock: true,
    stockCount: 15,
    features: [
      "LED Compatible",
      "Weather Resistant",
      "High Impact",
      "UV Stable",
    ],
    badges: ["LED Ready", "Weather Proof"],
    delivery: "Express Delivery",
    description:
      "Professional-grade acrylic designed for LED-backlit advertising displays.",
    specifications: {
      "LED Compatibility": "Yes",
      "Weather Rating": "IP65",
      "Impact Strength": "High",
      "UV Stability": "Excellent",
    },
    sizes: [
      {
        name: "3' × 6'",
        price: 199.99,
        inStock: true,
        stockCount: 25,
        dimensions: '36" × 72"',
      },
      {
        name: "4' × 8'",
        price: 299.99,
        inStock: true,
        stockCount: 20,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 399.99,
        inStock: true,
        stockCount: 15,
        dimensions: '60" × 120"',
      },
      {
        name: "6' × 12'",
        price: 599.99,
        inStock: true,
        stockCount: 8,
        dimensions: '72" × 144"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
    {
    id: 11,
    name: "R136",
    brand: "Advertise",
    category: "Interior Design",
    thickness: "6mm",
    finish: "Clear",
    size: "4' × 8'",
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    image: "/r136.png",
    rating: 4.8,
    reviews: 142,
    inStock: true,
    stockCount: 28,
    features: [
      "99.9% Clarity",
      "UV Resistant",
      "Scratch Resistant",
      "Easy Installation",
    ],
    badges: ["Premium", "Crystal Clear"],
    delivery: "Express Delivery",
    description:
      "Premium crystal-clear acrylic perfect for modern interior design applications.",
    specifications: {
      "Light Transmission": "99.9%",
      "UV Protection": "Yes",
      "Scratch Resistance": "High",
      Installation: "Easy",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 119.99,
        inStock: true,
        stockCount: 35,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 249.99,
        inStock: true,
        stockCount: 28,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 389.99,
        inStock: true,
        stockCount: 15,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },
      {
    id: 10,
    name: "502",
    brand: "Advertise",
    category: "Interior Design",
    thickness: "6mm",
    finish: "Clear",
    size: "4' × 8'",
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    image: "/502.png",
    rating: 4.8,
    reviews: 142,
    inStock: true,
    stockCount: 28,
    features: [
      "99.9% Clarity",
      "UV Resistant",
      "Scratch Resistant",
      "Easy Installation",
    ],
    badges: ["Premium", "Crystal Clear"],
    delivery: "Express Delivery",
    description:
      "Premium crystal-clear acrylic perfect for modern interior design applications.",
    specifications: {
      "Light Transmission": "99.9%",
      "UV Protection": "Yes",
      "Scratch Resistance": "High",
      Installation: "Easy",
    },
    sizes: [
      {
        name: "2' × 4'",
        price: 119.99,
        inStock: true,
        stockCount: 35,
        dimensions: '24" × 48"',
      },
      {
        name: "4' × 8'",
        price: 249.99,
        inStock: true,
        stockCount: 28,
        dimensions: '48" × 96"',
      },
      {
        name: "5' × 10'",
        price: 389.99,
        inStock: true,
        stockCount: 15,
        dimensions: '60" × 120"',
      },
      {
        name: "Custom Size",
        price: null,
        inStock: true,
        stockCount: null,
        dimensions: "Made to Order",
      },
    ],
  },













    {
      id: 10,
      name: "Classic Brown 570 ",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/570.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 11,
      name: "Royal Blue B703",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/b703.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },

  
    {
      id: 12,
      name: "Classic Brown 570 ",
      brand: "Nature Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/nt002.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 13,
      name: "Royal Blue B703",
      brand: "Heat Cut",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/nt001.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },



    {
      id: 14,
      name: "Light Brown SP-NC95",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior1.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
        {
      id: 15,
      name: "Foggy Brown SP-NB30",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior02.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },
           {
      id: 15,
      name: "Marine Blue SP-B857",
      brand: "Superior Series",
      category: "Structural",
      thickness: "12mm",
      finish: "Clear",
      size: "6' × 12'",
      price: 599.99,
      originalPrice: 719.99,
      discount: 17,
      image: "/superior03.jpg",
      rating: 4.8,
      reviews: 156,
      inStock: true,
      stockCount: 8,
      features: [
        "17x Stronger",
        "Fire Retardant",
        "Thermal Insulation",
        "Impact Resistant",
      ],
      badges: ["Industrial Grade", "Fire Safe"],
      delivery: "Express Delivery",
      description:
        "Heavy-duty structural acrylic for demanding construction applications.",
      specifications: {
        Strength: "17x Glass",
        "Fire Rating": "Class A",
        Thermal: "Excellent",
        Impact: "Superior",
      },
      sizes: [
        {
          name: "4' × 8'",
          price: 399.99,
          inStock: true,
          stockCount: 12,
          dimensions: '48" × 96"',
        },
        {
          name: "5' × 10'",
          price: 499.99,
          inStock: true,
          stockCount: 10,
          dimensions: '60" × 120"',
        },
        {
          name: "6' × 12'",
          price: 599.99,
          inStock: true,
          stockCount: 8,
          dimensions: '72" × 144"',
        },
        {
          name: "8' × 16'",
          price: 999.99,
          inStock: false,
          stockCount: 0,
          dimensions: '96" × 192"',
        },
        {
          name: "Custom Size",
          price: null,
          inStock: true,
          stockCount: null,
          dimensions: "Made to Order",
        },
      ],
    },

];
